/**:
  ros__parameters:
    update_rate: 100  # Hz
    
    # List of controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Controller specific parameters
joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2